# 使用 Windows 作为构建环境
image: Visual Studio 2022

# 克隆代码后安装 Node.js 和依赖
install:
  - ps: Install-Product node 18
  - npm install

# 运行 npm 构建脚本
build_script:
  - npm run build

# 生成 Windows 可执行文件
after_build:
  - npx electron-builder --win --x64

# 指定需要存储的构建产物
artifacts:
  - path: dist/*.exe
    name: Windows Installer
